### ISSUE TITLE
hi, i have a question about keyboard handling

### ISSUE THREAD

**Issue by sadounno** [stelleron/arcana2d#4]
can you put an example to how to handle keyboard inputs pleaze

**Comment by sadounno** [comment]
it's ok i dont see it before in Game context

here is an exemple
void Player::update(GameContext& ctx,float deltaTime)
{
	if (ctx.events.get().keyboardData.keyPressed[Key::W]) 
	{

		m_position.y -= deltaTime * m_speed.y;
	}

...

**Comment by stelleron** [comment]
You can either do that or use ctx.keyboard.get_key_pressed(Key::W). Also side note, I'm no longer maintaining this library as I moved onto Xenon, a very similar engine to this that I'm developing with more fleshed out features and less bugs, so I'd advise you use that instead!

**Comment by sadounno** [comment]
I use this engine because it is very easy to use since I am trying to learn OpenGL. I have also fixed a few bugs and added some features. In fact, I am using it as a starting point for my personal engine.
thank you for your job
